/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics;

/**
 *
 * @author korenciak.marek
 */
public class VehicleInfo extends javax.swing.JPanel {

    /**
     * Creates new form VehicleInfo
     */
    public VehicleInfo(String paVehicleName) {
        initComponents();
        vehicleNameLabel.setText(paVehicleName);
        reset();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vehicleWaitingALabel = new javax.swing.JLabel();
        vehicleNameLabel = new javax.swing.JLabel();
        vehicleAvgWaitingALabel = new javax.swing.JLabel();
        vehicleAvgWaitingBLabel = new javax.swing.JLabel();
        vehicleWaitingBLabel = new javax.swing.JLabel();
        vehicleStatus = new javax.swing.JLabel();
        vehicleActionTime = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Vehicle Info"));

        jLabel1.setText("Name");

        jLabel2.setText("Waiting time A total");

        jLabel3.setText("Waiting time B total");

        jLabel4.setText("Avg waiting time A");

        jLabel5.setText("Avg waiting time B");

        jLabel6.setText("Vehicle status");

        jLabel7.setText("Time of end action");

        vehicleWaitingALabel.setText("jLabel8");

        vehicleNameLabel.setText("jLabel9");

        vehicleAvgWaitingALabel.setText("jLabel10");

        vehicleAvgWaitingBLabel.setText("jLabel11");

        vehicleWaitingBLabel.setText("jLabel12");

        vehicleStatus.setText("jLabel13");

        vehicleActionTime.setText("jLabel14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vehicleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicleWaitingALabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vehicleWaitingBLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(vehicleStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(vehicleAvgWaitingALabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vehicleAvgWaitingBLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vehicleActionTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vehicleNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vehicleWaitingALabel))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vehicleWaitingBLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(vehicleAvgWaitingALabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vehicleAvgWaitingBLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vehicleStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(vehicleActionTime)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reset(){
        vehicleActionTime.setText("");
        vehicleAvgWaitingALabel.setText("");
        vehicleAvgWaitingBLabel.setText("");
        vehicleStatus.setText("");
        vehicleWaitingALabel.setText("");
        vehicleWaitingBLabel.setText("");
    }
    
    public void updateVehicel(Double paActionTime, double paAvgWaitingTimeA, double paAvgWaitingTimeB, 
            String paVehicleStatus, double paWaitingTimeA, double paWaitingTimeB){
        vehicleActionTime.setText(paActionTime+"");
        vehicleAvgWaitingALabel.setText(paAvgWaitingTimeA+"");
        vehicleAvgWaitingBLabel.setText(paAvgWaitingTimeB+"");
        vehicleStatus.setText(paVehicleStatus);
        vehicleWaitingALabel.setText(paWaitingTimeA+"");
        vehicleWaitingBLabel.setText(paWaitingTimeB+"");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel vehicleActionTime;
    private javax.swing.JLabel vehicleAvgWaitingALabel;
    private javax.swing.JLabel vehicleAvgWaitingBLabel;
    private javax.swing.JLabel vehicleNameLabel;
    private javax.swing.JLabel vehicleStatus;
    private javax.swing.JLabel vehicleWaitingALabel;
    private javax.swing.JLabel vehicleWaitingBLabel;
    // End of variables declaration//GEN-END:variables
}
